name: Джанго приложение yamdb

on: [push]

jobs:
  tests:
    # проверка кода на соответствие стандарту PEP8 (с помощью пакета flake8) и запуск pytest из репозитория yamdb_final;
    runs_on: ubuntu_latest

    steps:
      - uses: actions/checkout@v2

      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Установка зависимостей
        run: |
            python -m pip install --upgrade pip
            pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
            pip install -r api_yamdb/requirements.txt

      - name: Проверка с помощью flake8 и тестов django
        run: |
          python -m flake8
          python -m pytest


  build_push_to_doker_hub:
    # сборка и доставка докер-образа для контейнера web на Docker Hub;
  deploy:
    # автоматический деплой проекта на боевой сервер;
  send_to_telegam:
    # отправка уведомления в Telegram о том, что процесс деплоя успешно завершился.
